"""
chain.py

Contains all LangChain-related logic for generating stories.

Responsibilities:
1. Load shared environment variables.
2. Initialize the Gemini model.
3. Define the prompt template.
4. Build the LangChain chain.
5. Expose a reusable function for generating stories.
"""

from pathlib import Path

from dotenv import load_dotenv

from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import ChatPromptTemplate

# ------------------------------------------------------------------
# Load the shared .env file from the parent LangChain directory.
# ------------------------------------------------------------------

CURRENT_DIR = Path(__file__).resolve().parent
ROOT_DIR = CURRENT_DIR.parent.parent
ENV_PATH = ROOT_DIR / ".env"

load_dotenv(dotenv_path=ENV_PATH)

# ------------------------------------------------------------------
# Initialize the Gemini model.
# ------------------------------------------------------------------

llm = ChatGoogleGenerativeAI(
    model="gemini-2.5-flash",
    temperature=0.2,
)

# ------------------------------------------------------------------
# Define the prompt template.
# ------------------------------------------------------------------

prompt = ChatPromptTemplate.from_messages(
    [
        (
            "system",
            """
            You are an expert storyteller and a Subject Matter Expert (SME) in the Topic provided by the user.

            Write engaging, creative, and easy-to-read stories.

            Rules:
            - Keep the story under 500 words.
            - Use descriptive language.
            - Give the story a meaningful ending.
            - Keep it family friendly.
            """
        ),
        (
            "human",
            "{topic}"
        ),
    ]
)

# ------------------------------------------------------------------
# Build the LangChain pipeline using LCEL.
# ------------------------------------------------------------------

chain = prompt | llm

# ------------------------------------------------------------------
# Public function used by the FastAPI application.
# ------------------------------------------------------------------

def generate_story(topic: str) -> str:
    """
    Generate a story for the provided topic.

    Parameters
    ----------
    topic : str
        Story topic entered by the user.

    Returns
    -------
    str
        Story generated by Gemini.
    """

    response = chain.invoke(
        {
            "topic": topic
        }
    )

    return response.content